### ISSUE TITLE
SOAPUI crashes as soon as we run Testsuite

### ISSUE THREAD

**Issue by findmanish** [iamakshayshar/SoapUI-Extentter#13]
SOAPUI crashes as soon as we run Testsuite

SOAPUI version 5.7.0

**Comment by iamakshayshar** [comment]
@findmanish  : Can you please share more details about the issue. Share me the logs. I checked it on my machine and I am not facing any issue with TestSuite level execution. Please follow below setups. 
1. Go to SOAPUI installation directory and open cmd.
2. Navigate to folder BIN
3. In cmd, type soapui.bat.
4. This will open SOAPUI, trigger the TestSuite. 
5. Go back to CMD window and share the screenshot of the exception.

**Comment by iamakshayshar** [comment]
Closing this thread as no information received to debug the issue.
