### ISSUE TITLE
Project properties should not be returned in extent report

### ISSUE THREAD

**Issue by swapnil-git007** [iamakshayshar/SoapUI-Extentter#2]
Project properties should not be returned in extent report. It will reduce the chances of sharing the sensitive data to others.

**Comment by iamakshayshar** [comment]
This is a good suggestion. Will add this feature in next release.

**Comment by iamakshayshar** [comment]
Fixed in release [https://github.com/iamakshayshar/SoapUI-Extentter/releases/tag/v3.2](url)
