### ISSUE TITLE
L'utilisation de la bibliothèque Extentter rend impossible l'exécution de toutes les suites de tests dans le projet SOAPUI.

### ISSUE THREAD

**Issue by jmenioui** [iamakshayshar/SoapUI-Extentter#22]
Suite à l'intégration de la bibliothèque [Extentter-v5.1](https://github.com/iamakshayshar/SoapUI-Extentter/releases/tag/v5.1) pour générer des rapports d'API dans SOAPUI, le logiciel se ferme de manière inattendue lorsque je tente d'exécuter l'ensemble de tests de mon projet. Cependant, il est important de noter que lors de l'exécution d'une suite de tests individuelle, le rapport est correctement généré.

**Comment by iamakshayshar** [comment]
Hey @jmenioui I re-ran and checked it is working fine for me. Can you please open SOAPUI from cmd (Go to SOAPUI Installation folder > bin open Cmd and type soapui.bat) and after that trigger the execution and if it closes please share the screenshot of cmd window.

**Comment by iamakshayshar** [comment]
Can reproduce the issue. Fix in-progress

**Comment by iamakshayshar** [comment]
Hey @jmenioui, merci pour le problème. Correction de ce problème dans la dernière version Extentter-v5.1.1
Veuillez vérifier et faites-moi savoir si vous rencontrez toujours des problèmes.
