### ISSUE TITLE
To Print TestStep, Test case count in dashboard with Test Suite

### ISSUE THREAD

**Issue by automationbytes** [iamakshayshar/SoapUI-Extentter#3]
As of now, test suite count is getting added in dashboard. If possible can you please add a feature to print the test case and test step count too.

**Comment by iamakshayshar** [comment]
An investigation is required for this. But this is not the feature that Extent Report support now. It was with version 3. Labelling it as wontfix as of now.

**Comment by iamakshayshar** [comment]
This is not supported by ExtentReport itself, not able to fix this in current implementation
