### ISSUE TITLE
Soap Crash when running multiple test suites

### ISSUE THREAD

**Issue by JuanFe86** [iamakshayshar/SoapUI-Extentter#9]
Hi, when running multiple test suites the soap closes. Version 4.0

https://user-images.githubusercontent.com/60895251/145038791-33585fef-c40f-4a2c-b71b-7a4dbc6bd367.mp4

**Comment by iamakshayshar** [comment]
Thank you. 
I'll look into it and update.

**Comment by iamakshayshar** [comment]
@JuanFe86 : This could be of different reason. I tried it in my machine and it worked fine, with Parallel execution and sequential execution. Try to debug using below steps, 
1. Go to SOAPUI installation directory, (typically it would be C:\Program Files\SmartBear\SoapUI-5.6.0)
2. Then navigate to Bin folder and open command prompt at this location.
3. Then open soapui.bat file. This will open SOAPUI UI interface.
4. Try executing a project, if this fails and soapui closes ahead back to CMD window and check the error.
5. Debug the issue and share it with me as well. I will try to help you with the solution.
